name: int_grad_corr
channels:
    - pytorch
    - nvidia
    - defaults
dependencies:
    - python=3.10
    - jupyter
    # Sciences
    - numpy
    - matplotlib
    - scikit-learn
    # Neural Networks
    - pytorch::pytorch=2.4
    - pytorch::pytorch-cuda=12.4
    - pytorch::torchvision
    - tensorboard
    # Image
    - pillow
    # Others
    - h5py
    - tqdm
