name: int_grad_corr
channels:
    - pytorch
    - nvidia
    - defaults
dependencies:
    - python=3.10
    - jupyter
    # Sciences
    - numpy
    - scipy
    - matplotlib
    # Neural Networks
    - pytorch::pytorch=2.1
    - pytorch::pytorch-cuda=12.1
    - tensorboard
    # Others
    - tqdm
