name: int_grad_corr
channels:
    - defaults
dependencies:
    - python
    - jupyter
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - tqdm
    # Pip
    - pip
    - pip:
        - torch --index-url="https://download.pytorch.org/whl/cpu"
        - torchvision --index-url="https://download.pytorch.org/whl/cpu"
        - standard-imghdr  # For tensorboard
        - tensorboard
