name: int_grad_corr
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.10
    - jupyter
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - tqdm
    - pytorch::pytorch=2.2  # Mac Intel limitated to 2.2
    - pytorch::torchvision
    - tensorboard
