name: Deploy Sphinx to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Sphinx
        run: |
          pip install sphinx pydata-sphinx-theme sphinx-copybutton sphinxcontrib-bibtex
      - name: Install IGC
        run: |
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build -M html ./docs/source/ ./docs/build/
      - name: Set up Pages
        uses: actions/configure-pages@v5
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
